- .github/workflows/ci.yml
- config.toml
> add google ansible

- content/zh/docs/concepts/collection-resource.md
- content/zh/docs/usage/search/searching-collection-resource.md
- content/zh/docs/usage/search/searching-multi-cluster.md
- content/zh/docs/usage/search/searching-specified-cluster.md
> add usage doc for specified cluster search

- content/zh/docs/installation/configurate/configurate-internalstorage.md
- content/zh/docs/installation/kubectl-apply.md
> update installation docs

- content/zh/docs/usage/access-clusterpedia.md
- content/zh/docs/usage/import-clusters.md
- content/zh/docs/usage/sync-resources.md
> update usage docs

- content/zh/docs/usage/search/_index.md
- content/zh/docs/usage/search/searching-multi-cluster.md
> update usage docs for search

- content/zh/docs/concepts/collection-resource.md
- content/zh/docs/usage/search/_index.md
- content/zh/docs/usage/search/collection-resource.md
- content/zh/docs/usage/search/multi-cluster.md
- content/zh/docs/usage/search/specified-cluster.md
> change the filename of the search docs

- content/en/docs/installation/kubectl-apply.md
- content/zh/docs/installation/kubectl-apply.md
> update to v0.0.9-alpha

- content/en/docs/usage/access-clusterpedia.md
- content/zh/docs/usage/access-clusterpedia.md
> update gen-clusterconfigs.sh link

- content/en/docs/usage/search/multi-cluster.md
- content/zh/docs/usage/search/_index.md
- content/zh/docs/usage/search/multi-cluster.md
> fix search docs

- content/en/blog/_index.md
- content/en/blog/upgrade-to-0.1.0.md
- content/zh/blog/_index.md
- content/zh/blog/upgrade-to-0.1.0.md
> blog: add upgrade to clusterpedia 0.1.0

- content/en/blog/upgrade-to-0.1.0.md
- content/zh/blog/upgrade-to-0.1.0.md
> blog: fix bak command when upgrade

- content/en/docs/installation/kubectl-apply.md
- content/zh/docs/installation/kubectl-apply.md
The operation sequence is wrong, so it is submitted for repair this time.
> fix docs of clusterpedia with installtion

- content/en/docs/release-notes/_index.md
- content/zh/docs/release-notes/_index.md
> link release notes to github

- content/en/docs/installation/kubectl-apply.md
- content/zh/docs/installation/kubectl-apply.md
> add uninstall doc

- content/en/docs/installation/kubectl-apply.md
- content/zh/docs/installation/kubectl-apply.md
> update to 0.2.0

- content/en/docs/usage/access-clusterpedia.md
- content/zh/docs/usage/access-clusterpedia.md
I found some problem and fixed it.
> update doc version

- content/en/docs/usage/search/multi-cluster.md
- content/zh/docs/usage/search/multi-cluster.md
> Modified multi-cluster.md

- content/zh/docs/usage/import-clusters.md
- content/zh/docs/usage/search/multi-cluster.md
Signed-off-by: 刘复佳 <1030923822@qq.com>
> Modify typos in documents

- content/en/docs/usage/import-clusters.md
- content/zh/docs/usage/import-clusters.md
Signed-off-by: luozhengtest <476192920@qq.com>
> Update the Access Cluster Get CA and TOKEN commands

- content/zh/docs/concepts/collection-resource.md
- content/zh/docs/features/_index.md
- content/zh/docs/features/prune_fields.md
- content/zh/docs/features/raw_sql_query.md
- content/zh/docs/features/remaining_item_count.md
- content/zh/docs/features/sync_all_custom_resources.md
- content/zh/docs/features/sync_all_resources.md
- content/zh/docs/installation/configurate/configurate-internalstorage.md
- content/zh/docs/installation/kubectl-apply.md
- content/zh/docs/usage/search/_index.md
- content/zh/docs/usage/sync-resources.md
> zh: update docs to 0.3.0

- content/en/docs/concepts/collection-resource.md
- content/en/docs/features/_index.md
- content/en/docs/features/prune-fields.md
- content/en/docs/features/raw-sql-query.md
- content/en/docs/features/remaining-item-count.md
- content/en/docs/features/sync-all-custom-resources.md
- content/en/docs/features/sync-all-resources.md
- content/en/docs/installation/configuration/configure-internalstorage.md
- content/en/docs/installation/kubectl-apply.md
- content/en/docs/usage/access-clusterpedia.md
- content/en/docs/usage/search/_index.md
- content/en/docs/usage/sync-resources.md
> update docs to 0.3.0

- content/en/blog/clusterpedia-with-kubectl.md
- content/zh/blog/clusterpedia-with-kubectl.md
> add blog clusterpedia-with-kubectl

- content/en/blog/clusterpedia-0.1.0.md
- content/en/blog/clusterpedia-0.2.0.md
- content/zh/blog/clusterpedia-0.1.0.md
- content/zh/blog/clusterpedia-0.2.0.md
- content/zh/blog/csdn.md
- content/zh/blog/install-with-helm.md
- content/zh/blog/landscape.md
- content/zh/blog/search-by-multi-cluster.md
> add some blogs

- content/en/docs/installation/kubectl-apply.md
- content/zh/docs/installation/kubectl-apply.md
Signed-off-by: wuyingjun <wuyingjun_yewu@cmss.chinamobile.com>
> Enhancement: use kubectl apply instead of create while deploying storage component

- config.toml
- content/en/_index.html
- content/zh/_index.html
> update slack link

- content/en/_index.html
- content/zh/_index.html
for https://github.com/cncf/toc/issues/853
> add cncf sandbox info

- content/zh/docs/installation/kubectl-apply.md
Added some punctuations such as periods and Enter.
> [zh] text optimization: installation/kubectl-apply.md

- content/zh/docs/concepts/cluster-import-policy.md
- content/zh/docs/concepts/cluster-sync-resources.md
- content/zh/docs/concepts/collection-resource.md
- content/zh/docs/concepts/pediacluster.md
- content/zh/docs/usage/search/_index.md
- content/zh/docs/usage/search/collection-resource.md
- content/zh/docs/usage/sync-resources.md
> zh: update docs for ClusterSyncResources and Any CollectionResource

- content/en/docs/concepts/cluster-sync-resources.md
- content/en/docs/concepts/collection-resource.md
- content/en/docs/concepts/pediacluster.md
- content/en/docs/usage/search/_index.md
- content/en/docs/usage/search/collection-resource.md
- content/en/docs/usage/sync-resources.md
zh: https://github.com/clusterpedia-io/website/pull/50
> update docs for ClusterSyncResources and Any CollectionResource

- content/zh/docs/concepts/cluster-import-policy.md
- content/zh/docs/usage/access-clusterpedia.md
- content/zh/docs/usage/interfacing-to-multi-cloud-platforms.md
- content/zh/docs/usage/sync-resources.md
> zh: add ClusterImportPolicy and PediaClusterLifecycle docs

- content/en/docs/concepts/cluster-import-policy.md
- content/en/docs/usage/access-clusterpedia.md
- content/en/docs/usage/interfacing-to-multi-cloud-platforms.md
- content/en/docs/usage/sync-resources.md
issue: https://github.com/clusterpedia-io/website/pull/52
> add ClusterImportPolicy and PediaClusterLifecycle docs

- content/en/docs/installation/kubectl-apply.md
- content/en/docs/usage/access-clusterpedia.md
- content/zh/docs/installation/kubectl-apply.md
- content/zh/docs/usage/access-clusterpedia.md
> update docs to 0.4.0

- content/en/docs/installation/kubectl-apply.md
- content/en/docs/usage/access-clusterpedia.md
- content/zh/docs/installation/kubectl-apply.md
- content/zh/docs/usage/access-clusterpedia.md
> update to 0.4.1

- content/en/blog/interfacing-to-cluster-api.md
> blog: interfacing to cluster api

- content/en/blog/interfacing-to-cluster-api.md
> fix interfacing-to-cluster-api blog

- content/zh/blog/interfacing-to-cluster-api.md
> zh: add interfacing to cluster api blog

- content/en/docs/usage/interfacing-to-multi-cloud-platforms.md
- content/zh/docs/usage/interfacing-to-multi-cloud-platforms.md
> add cluster api to interfacing-to-multi-platforms doc

- content/en/docs/concepts/cluster-import-policy.md
- content/zh/docs/concepts/cluster-import-policy.md
> update cluster import policy

- content/en/docs/installation/kubectl-apply.md
- content/en/docs/usage/access-clusterpedia.md
- content/zh/docs/installation/kubectl-apply.md
- content/zh/docs/usage/access-clusterpedia.md
> update docs to 0.5.0

- content/en/docs/usage/interfacing-to-multi-cloud-platforms.md
- content/zh/docs/usage/interfacing-to-multi-cloud-platforms.md
> add vcluster to interfacing-to-multi-platforms doc

- content/en/docs/installation/helm.md
- content/zh/docs/installation/helm.md
> link helm doc to clusterpedia repo

- content/en/docs/features/_index.md
- content/en/docs/features/health-checker-with-standalone-tcp.md
- content/zh/docs/features/_index.md
- content/zh/docs/features/health-checker-with-standalone-tcp.md
https://github.com/clusterpedia-io/clusterpedia/pull/459
> docs/feature: add HealthCheckerWithStandaloneTCP

- content/en/blog/install-with-helm.md
- content/en/docs/installation/kubectl-apply.md
- content/zh/blog/install-with-helm.md
- content/zh/docs/installation/kubectl-apply.md
Signed-off-by: ONE7live <wangqi_yewu@cmss.chinamobile.com>
**What type of PR is this?**
/kind documentation
**What this PR does / why we need it**:
When I uninstalled clusterpedia according to the documentation and reinstalled, the documentation command was missing a required parameter for deleting a folder.
> add command options when removing PV

- content/en/docs/installation/kubectl-apply.md
- content/en/docs/usage/access-clusterpedia.md
- content/zh/docs/installation/kubectl-apply.md
- content/zh/docs/usage/access-clusterpedia.md
> update to 0.6.0

- content/en/docs/advanced-features/_index.md
- content/en/docs/advanced-features/custom_storage_layer.md
> add custom_storage_layer.md

- content/en/docs/installation/helm.md
- content/zh/docs/installation/helm.md
update use helm link, old link 404
> update use helm link

- assets/scss/_variables_project.scss
- content/en/_index.html
- content/zh/_index.html
> fix: home cloudnative logo overflow

- package-lock.json
Updated the outdated `package-lock.json`
> chore: update lock file for deps
